import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {AiFillLinkedin, AiFillGithub, AiFillMail} from 'react-icons/ai'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Malik Baker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons'>malbaker</h1>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill className='cursor-pointer text-2xl'/>
              </li>
              <li>
                <a 
                  className='bg-gradient-to-r from-indigo-600 to-indigo-400 text-white px-4 py-2 rounded-md ml-8' 
                  href="/Resume.pdf" target="_blank" rel="noopener noreferrer">
                Resume</a>
              </li>
            </ul>
          </nav>
          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-indigo-600 font-medium'>
              Hi, I&apos;m Malik
            </h2>
            <h3 className='text-2xl py-2'>Student, developer, thought-haver.</h3>
            <p className='text-md py-5 leading-8 text-gray-800'>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Gravida quis blandit turpis cursus in. Venenatis urna cursus eget nunc scelerisque. Etiam dignissim diam quis enim. Congue eu consequat ac felis donec. Egestas dui id ornare arcu odio. Mattis vulputate enim nulla aliquet porttitor lacus luctus accumsan tortor. Amet porttitor eget dolor morbi non arcu risus. At tempor </p>
          </div>

          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
            <a href="https://www.linkedin.com/in/malbaker" target="_blank" rel="noreferrer noopener"><AiFillLinkedin/></a>
            <a href="https://www.github.com/malbaker" target="_blank" rel="noreferrer noopener"><AiFillGithub/></a>
            <a href="mailto:malikbaker75@gmail.com" target="_blank" rel="noreferrer noopener"><AiFillMail/></a>
          </div>
          
        </section>
      </main>
    </div>
  )
}
